#!/bin/bash
# Generate daily development report for Claude context

# Get today's date
TODAY=$(date +%Y-%m-%d)
REPORT_FILE=".ai/reports/daily_${TODAY}.md"

# Ensure reports directory exists
mkdir -p .ai/reports

# Get git user info
GIT_USER=$(git config user.name || echo "Developer")

# Generate report
cat > "$REPORT_FILE" << EOF
# Daily Development Report - $TODAY
Generated: $(date '+%Y-%m-%d %H:%M:%S')
Developer: $GIT_USER

## Summary
- Current Branch: $(git branch --show-current)
- Total Commits Today: $(git log --since="1 day ago" --oneline | wc -l)
- Files Changed: $(git diff --stat HEAD@{1.day.ago} 2>/dev/null | tail -1 || echo "First day")

## Commits Today
$(git log --since="1 day ago" --pretty=format:"- [%h] %s (%cr)" --author="$GIT_USER")

## Features Completed
$(git log --since="1 day ago" --grep="^feat" --pretty=format:"- %s" --author="$GIT_USER")

## Bugs Fixed  
$(git log --since="1 day ago" --grep="^fix" --pretty=format:"- %s" --author="$GIT_USER")

## Files Modified
$(git log --since="1 day ago" --name-only --pretty=format:"" | sort | uniq | grep -v '^$' | head -20)

## Code Statistics
$(git diff --shortstat HEAD@{1.day.ago} 2>/dev/null || echo "No previous commits to compare")

## Tomorrow's Context
- Branch: $(git branch --show-current)
- Uncommitted Files: $(git status --porcelain | wc -l)
- Stashed Changes: $(git stash list | wc -l)

## Open Tasks
$(grep -h "^- \[ \]" .ai/current_sprint.md 2>/dev/null | head -10 || echo "No tasks found in sprint file")

## Notes for Tomorrow
- Remember to pull latest changes before starting
- Check .ai/current_sprint.md for priority tasks
- Review any failing tests or build issues

---
Report generated by daily_report.sh
EOF

echo "✅ Daily report generated: $REPORT_FILE"
echo ""
echo "Summary:"
echo "- Commits today: $(git log --since="1 day ago" --oneline | wc -l)"
echo "- Current branch: $(git branch --show-current)"
echo "- Files with changes: $(git status --porcelain | wc -l)"

# Also update the development log
echo "" >> .ai/logs/development_log.md
echo "## Daily Summary - $TODAY" >> .ai/logs/development_log.md
echo "- Total commits: $(git log --since="1 day ago" --oneline | wc -l)" >> .ai/logs/development_log.md
echo "- Features: $(git log --since="1 day ago" --grep="^feat" --oneline | wc -l)" >> .ai/logs/development_log.md
echo "- Fixes: $(git log --since="1 day ago" --grep="^fix" --oneline | wc -l)" >> .ai/logs/development_log.md
echo "---" >> .ai/logs/development_log.md